services:
  greta-pipeline:
    image: ghcr.io/lbnl-ai88/greta-pipeline-docker:latest
    user: root
    volumes:
      - ./config.yaml:/greta-pipeline/config.yaml:ro
      - ./static_inputs:/greta-pipeline/static_inputs:ro
      - type: bind
        source: ./output
        target: /greta-pipeline/output
        bind: 
          create_host_path: true

